[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "evolution-parental-instinct"
version = "0.0.1"
requires-python = ">=3.13"
dependencies = []

[project.urls]
Homepage = "https://github.com/Muna-Louis-Nwugo/Evolution-Parental-Instinct"

[tool.maturin]
python-source = "python"
module-name = "simulate"
